# Generated by Django 5.0.2 on 2024-02-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_teacher_student_first_name_student_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('First_Name', models.CharField(max_length=30, null=True)),
                ('Second_Name', models.CharField(max_length=30, null=True)),
                ('year', models.IntegerField(null=True)),
                ('class_time', models.IntegerField(null=True)),
            ],
        ),
    ]
