# Generated by Django 5.0.2 on 2024-02-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('Author', models.CharField(max_length=30, null=True)),
                ('Date_created', models.DateField(null=True)),
            ],
        ),
    ]
